



// MIDI TIME CLOCK
#define 	MIDICLOCK_START		0xFA
#define 	MIDICLOCK_CONTINUE	0xFB
#define 	MIDICLOCK_STOP		0xFC
#define		MIDICLOCK_CLOCK		0xF8


// MIDI TIME CLOCK
#define 	MIDICLOCK_START		0xFA
#define 	MIDICLOCK_CONTINUE	0xFB
#define 	MIDICLOCK_STOP		0xFC
#define		MIDICLOCK_CLOCK		0xF8
